feat: added router and ErrorBoundary
Shadow-Shamans/first-race pull request #20
Opened 2023-03-25 11:17 UTC by stevenKirill

### Какую задачу решаем
Добавлены роуты, обработка ошибок в дочерних компонентах
https://github.com/Shadow-Shamans/first-race/issues/4
https://github.com/Shadow-Shamans/first-race/issues/13

### Скриншоты/видяшка (если есть)
<img width="1403" alt="Screenshot 2023-03-25 at 14 14 25" src="https://user-images.githubusercontent.com/47239173/227714196-c2f5778d-51fe-4d82-9dc7-0511198757a1.png">

2023-03-25 11:37 UTC, vaskes79 commented
@stevenKirill надо поправить тесты

2023-03-25 12:15 UTC, vaskes79 reviewed
Если до вас директория была пуста, после создания модуля, удалити из неё файл .keep

2023-03-25 12:15 UTC, vaskes79 commented on packages/client/src/pages/Forum/index.tsx
Надо вынести весь код из index.tsx в файл Forum.tsx. Файл index.tsx конрветровать в простой index.ts и использовать только для экспортов содержимого модуля наружу. По анологии как сделано в app. так же важно чтобы внутри файла Forum.tsx export был `export const Form...` а в index, должна быть возможность экспортировать основной модуль как дефолтный и простым импортом. `export default Forum` export {*} from './Forum', либо кокретезировать export { Forum }

2023-03-25 13:08 UTC, vaskes79 requested changes

2023-03-25 13:08 UTC, vaskes79 commented on packages/client/src/router/index.tsx
> +const Login = AsyncComponent(() => import('../pages/Login'))
тут наши импорты, на алиасах не работают?

2023-03-25 13:08 UTC, vaskes79 commented on packages/client/src/shared/HOCS/PrivateRoute.tsx
> +type PrivateRouteProps = {
Имя типа начинается с `IProps` и для пропосов мы используем interface

2023-03-25 13:08 UTC, vaskes79 commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +type DynamicImportType = () => Promise<{ default: React.ComponentType }>
имя типа начинаесть c `T`

2023-03-25 13:08 UTC, vaskes79 commented on packages/client/src/shared/providers/ThemeProvider.tsx
> +export type Props = {
`IProps`

2023-03-25 13:08 UTC, vaskes79 commented on packages/client/src/shared/utils/ErrorBoundary.tsx
> +class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
Можешь конвертировать его в функциональный?

2023-03-25 17:36 UTC, dahah-babah reviewed
@stevenKirill, проделана отличная работа 👍

Есть пара моментов, на которые хочу обратить внимание:

1. Пустые строки: оставила пару комментов, но прошу пробежаться по твоему коду еще разок и добавить пустые строки, чтобы отделить объявление переменных от других действий и добавить их между блоками одного уровня, я правда думаю, что так код станет более чистым и читаемым :) 
2. Пустые строки: также убрать лишние пустые строки между импортами и самим компонентом
3. Занести в притиер конфиг опцию с `;`, чтобы весь код имел одинаковый стиль

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/app/App.test.tsx
> +) as jest.Mock;
Давайте определимся, мы будем использовать `;` в конце строки или нет, а то тут есть, в другом месте нет. Предлагаю добавить правило в конфиг притиера `"semi": true/false` и придерживаться единого стиля в коде)

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/features/AppMenu/index.tsx
> +
Давай уберем лишние пустые строки между импортами и компонентом?

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/features/AppMenu/index.tsx
> +      onClick={onClick}
Я описывала нейминг функций в [регламенте](https://github.com/Shadow-Shamans/first-race/wiki/Регламент), предлагаю обработчик в компоненте обозвать `handleClick` и передвинуть его в конец всех пропсов

```tax
<Menu
  ...
  onClick={handleClick}
/> 
```

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/features/AppMenu/index.tsx
> +import { useState, FC } from 'react';
Мы разве в `index`-файле не только экспорты описываем?

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/features/AppMenu/index.tsx
> +const AppMenu: FC = () => {
Может просто `Menu` оставим, мне кажется тут `App` - избыточно? Если пугает, что в анте тоже есть `Menu`, тогда его можно в этом компоненте заимпортить как `AntdMenu`, оно же все равно только тут будет использоваться

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/pages/Main/index.tsx
> +  const { handleChangeTheme, themeName } = useTheme()
Давай в этом месте отделим определение константы от `return` пустой строкой?

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/pages/Main/index.tsx
> +    <Card style={{ width: 'max-content' }}>
Кажется тут литер не сработал, проблема со вложенностью

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/pages/Main/index.tsx
> +    <Card style={{ width: 'max-content' }}>
Давайте постараемся максимально исключить использование инлайновых стилей, это может привести к ошибкам в будущем. Пока кода мало, можем оставить, но я предлагаю добавить тудушку, чтобы ее убрать, либо сразу использовать тут класс

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/pages/Main/index.tsx
> +      <h1>antd version: {version}</h1>
Давайте ставить пустые строки между блоками одной вложенности - код становится более читабельным)

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/router/index.tsx
> +
Давай уберем тут одну пустую строку, в идеале можно настроить литер под это дело, но это можно опустить или сделать в другой задаче)

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/router/index.tsx
> +      <Route path="/main" element={<Main />} />
Для раутов не нужно указывать `exact={true}`?

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +const AsyncComponent = (importComponent: DynamicImportType) => class extends Component {
А почему тут используется классовый компонент, а не функциональный как и во всех других местах?

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +    importComponent().then((cmp) => {
Что есть `cmp`? Давайте не сокращать названия)

2023-03-25 17:36 UTC, dahah-babah commented on packages/client/src/shared/HOCS/PrivateRoute.tsx
> +type PrivateRouteProps = {
Именно так, давайте также не добавлять лишний контекст `PrivateRouteProps` -> `IProps`, мы же никуда не экспортим это, тут и так понятно, что это пропсы для этого компонента)

2023-03-25 17:39 UTC, dahah-babah commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +import React, { Component } from 'react'
А почему только `HOCS` названо капсом? Нам просто `hocs` не подойдет?

2023-03-26 08:20 UTC, stevenKirill commented on packages/client/src/pages/Forum/index.tsx
ок

2023-03-26 08:21 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
да какая разница lazy использовать или самописный  async, одно и тоже

2023-03-26 08:31 UTC, stevenKirill commented on packages/client/src/features/AppMenu/menu.module.css
ок

2023-03-26 08:33 UTC, stevenKirill commented on packages/client/src/router/index.tsx
> +const Login = AsyncComponent(() => import('../pages/Login'))
тут нет а зачем тут алиасы? тут  нету большой вложенности папок

2023-03-26 08:33 UTC, stevenKirill commented on packages/client/src/shared/HOCS/PrivateRoute.tsx
> +type PrivateRouteProps = {
ок

2023-03-26 08:34 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +type DynamicImportType = () => Promise<{ default: React.ComponentType }>
ок

2023-03-26 08:34 UTC, stevenKirill commented on packages/client/src/shared/providers/ThemeProvider.tsx
> +export type Props = {
ок

2023-03-26 08:35 UTC, stevenKirill commented on packages/client/src/shared/utils/ErrorBoundary.tsx
> +class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
в функциональный не получиться конвертировать так как у хуков нету метода componentDidCatch, тут только на классах

2023-03-26 08:36 UTC, stevenKirill commented on packages/client/src/app/App.test.tsx
> +) as jest.Mock;
я вообще ставлю всегда, я линтер не ставил там какой стоит тот и юзается, он про ; ниче не говорит, там не настроено просто это

2023-03-26 08:36 UTC, stevenKirill commented on packages/client/src/features/AppMenu/index.tsx
> +
ок

2023-03-26 08:36 UTC, stevenKirill commented on packages/client/src/features/AppMenu/index.tsx
> +      onClick={onClick}
копипаст с доки был просто, забыл

2023-03-26 08:38 UTC, stevenKirill commented on packages/client/src/features/AppMenu/index.tsx
> +import { useState, FC } from 'react';
ок

2023-03-26 08:39 UTC, stevenKirill commented on packages/client/src/features/AppMenu/index.tsx
> +const AppMenu: FC = () => {
ок просто Menu

2023-03-26 08:41 UTC, stevenKirill commented on packages/client/src/router/index.tsx
> +
ок

2023-03-26 08:41 UTC, stevenKirill commented on packages/client/src/router/index.tsx
> +      <Route path="/main" element={<Main />} />
не обязательно

2023-03-26 08:41 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +import React, { Component } from 'react'
переименовал в hocs

2023-03-26 08:42 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +    importComponent().then((cmp) => {
это component

2023-03-26 08:43 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +const AsyncComponent = (importComponent: DynamicImportType) => class extends Component {
для разнообразия )

2023-03-26 08:44 UTC, vaskes79 commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
ок. Я просто подумал, что если использовать `lazy` и `Suspence`  мы будет иметь тоже самое, но в функциональном стиле, без слассовых компонентов. И я могу ошибаться но по моем такм мы получим чанк, а в твоем варинате, не знаю.

```
<Suspense fallback={<Loading />}>
  <SomeComponent />
</Suspense>
```

2023-03-26 08:46 UTC, vaskes79 commented on packages/client/src/router/index.tsx
> +const Login = AsyncComponent(() => import('../pages/Login'))
Все что находится за пределами модуля, долно импортироваться черз алиас, все что внутри модуля импортируется по относительным путям.

2023-03-26 08:49 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
перепишу на lazy

2023-03-26 08:52 UTC, vaskes79 commented on packages/client/src/app/App.test.tsx
> +) as jest.Mock;
завел на это задачу https://github.com/Shadow-Shamans/first-race/issues/21

2023-03-26 09:01 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
> +const AsyncComponent = (importComponent: DynamicImportType) => class extends Component {
сделаю на lazy

2023-03-26 09:05 UTC, stevenKirill commented on packages/client/src/shared/HOCS/AsyncComponent.tsx
в моем варианте тоже будет чанк, но я переписал на lazy

2023-03-26 09:08 UTC, stevenKirill commented on packages/client/src/pages/Main/index.tsx
> +  const { handleChangeTheme, themeName } = useTheme()
не понимаю о чем речь

2023-03-26 09:10 UTC, stevenKirill commented on packages/client/src/pages/Main/index.tsx
> +    <Card style={{ width: 'max-content' }}>
ок

2023-03-26 09:21 UTC, stevenKirill commented on packages/client/src/pages/Main/index.tsx
> +    <Card style={{ width: 'max-content' }}>
вынес стили

2023-03-26 09:22 UTC, stevenKirill commented on packages/client/src/pages/Main/index.tsx
> +      <h1>antd version: {version}</h1>
типо шаблонной строкой все писать в h1 ?

2023-03-26 10:23 UTC, vaskes79 approved these changes

2023-03-26 10:38 UTC, dahah-babah commented on packages/client/src/pages/Main/index.tsx
> +  const { handleChangeTheme, themeName } = useTheme()
Я имею в виду перед `return` добавлять пустую строку

2023-03-26 10:40 UTC, dahah-babah commented on packages/client/src/pages/Main/index.tsx
> +      <h1>antd version: {version}</h1>
Это все вкусовщина, но я об этом:

```tax
<>
  <h1>{...}</h1>
  // пустая строка
  <div> ...</div>
</>
```

2023-03-26 10:49 UTC, dahah-babah approved these changes

2023-03-26 19:45 UTC, Kventi111 commented on packages/client/src/features/AppMenu/Menu.tsx
> +    setCurrent(e.key)
Тут лучше деструктуризировать.
и юзать

2023-03-26 19:50 UTC, Kventi111 commented on packages/client/src/features/AppMenu/index.tsx
> +import { Menu } from './Menu'
здесь можно сразу
```suggestion
export default { Menu } from './Menu'
```

2023-03-26 19:50 UTC, Kventi111 commented on packages/client/src/pages/Forum/index.ts
> +import { Forum } from './Forum'
```suggestion
export default { Forum } from './Forum'
```

2023-03-26 19:50 UTC, Kventi111 commented on packages/client/src/pages/Game/index.tsx
> +import { Game } from './Game'
```suggestion
export default { Game } from './Game'
```

2023-03-26 19:50 UTC, Kventi111 commented on packages/client/src/shared/utils/index.ts
> +}
лучше в index файле ничего не разрабатывать 
а сделать файлик с названием утилиты

2023-03-26 20:06 UTC, vaskes79 commented on packages/client/src/pages/Forum/index.ts
> +import { Forum } from './Forum'
@Kventi111 а если мы в будущем захотим экспортировать еще что нибудь из форум? А так мы явно даем на ружу выставляем дефолтный экспорт, возможность экспорта по имени и возможность достать еще что либо из Forum. Нет?

2023-03-27 06:21 UTC, stevenKirill commented on packages/client/src/shared/utils/index.ts
> +}
ок

2023-03-27 06:22 UTC, stevenKirill commented on packages/client/src/features/AppMenu/Menu.tsx
> +    setCurrent(e.key)
ок

2023-03-27 06:24 UTC, stevenKirill commented on packages/client/src/features/AppMenu/index.tsx
> +import { Menu } from './Menu'
мы решили в команде экспорт и дефолтный делать и обычный

2023-03-27 06:27 UTC, stevenKirill commented on packages/client/src/pages/Game/index.tsx
> +import { Game } from './Game'
решили в команде делать экспорт и дефолтный и обычный

2023-03-27 08:15 UTC, Kventi111 commented on packages/client/src/pages/Forum/index.ts
> +import { Forum } from './Forum'
Ну если задумка такая то окей )

2023-03-27 08:15 UTC, Kventi111 approved these changes

2023-03-27 08:17 UTC, merged